    apiVersion: v1
    kind: Pod
    metadata:
      name: config-pod
    spec:
      containers:
      - name: test-container
        image: busybox
        command: [ "/bin/sh", "-c", "env && sleep 3600" ]
        envFrom:
        - configMapRef:
            name: app-config