apiVersion: v1
kind: Pod
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Pod","metadata":{"annotations":{},"labels":{"app":"demo"},"name":"resource-pod","namespace":"default"},"spec":{"containers":[{"args":["-cpus","1","-mem-total","150Mi","-mem-alloc-size","10Mi","-mem-alloc-sleep","1s"],"image":"vish/stress","name":"stress-container","resources":{"limits":{"cpu":"500m","memory":"128Mi"},"requests":{"cpu":"250m","memory":"64Mi"}}}]}}
  creationTimestamp: "2026-04-21T11:53:31Z"
  generation: 1
  labels:
    app: demo
  name: resource-pod
  namespace: default
  resourceVersion: "122118"
  uid: 817a4181-b790-46a7-bd9a-7e297be42f0d
spec:
  containers:
  - args:
    - -cpus
    - "1"
    - -mem-total
    - 150Mi
    - -mem-alloc-size
    - 10Mi
    - -mem-alloc-sleep
    - 1s
    image: vish/stress
    imagePullPolicy: Always
    name: stress-container
    resources:
      limits:
        cpu: 500m
        memory: 250Mi
      requests:
        cpu: 250m
        memory: 128Mi
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-4ll6d
      readOnly: true
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  nodeName: aks-nodepool1-11368919-vmss000001
  preemptionPolicy: PreemptLowerPriority
  priority: 0
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext: {}
  serviceAccount: default
  serviceAccountName: default
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  - effect: NoSchedule
    key: node.kubernetes.io/memory-pressure
    operator: Exists
  volumes:
  - name: kube-api-access-4ll6d
    projected:
      defaultMode: 420
      sources:
      - serviceAccountToken:
          expirationSeconds: 3607
          path: token
      - configMap:
          items:
          - key: ca.crt
            path: ca.crt
          name: kube-root-ca.crt
      - downwardAPI:
          items:
          - fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
            path: namespace
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2026-04-21T11:53:33Z"
    observedGeneration: 1
    status: "True"
    type: PodReadyToStartContainers
  - lastProbeTime: null
    lastTransitionTime: "2026-04-21T11:53:31Z"
    observedGeneration: 1
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: "2026-04-21T14:18:40Z"
    message: 'containers with unready status: [stress-container]'
    observedGeneration: 1
    reason: ContainersNotReady
    status: "False"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: "2026-04-21T14:18:40Z"
    message: 'containers with unready status: [stress-container]'
    observedGeneration: 1
    reason: ContainersNotReady
    status: "False"
    type: ContainersReady
  - lastProbeTime: null
    lastTransitionTime: "2026-04-21T11:53:31Z"
    observedGeneration: 1
    status: "True"
    type: PodScheduled
  containerStatuses:
  - allocatedResources:
      cpu: 250m
      memory: 64Mi
    containerID: containerd://23163109a52434961736d6f77f3b7321afa4b35921aae6279cdd0044bd1439db
    image: docker.io/vish/stress:latest
    imageID: docker.io/vish/stress@sha256:b6456a3df6db5e063e1783153627947484a3db387be99e49708c70a9a15e7177
    lastState:
      terminated:
        containerID: containerd://23163109a52434961736d6f77f3b7321afa4b35921aae6279cdd0044bd1439db
        exitCode: 137
        finishedAt: "2026-04-21T14:18:39Z"
        reason: OOMKilled
        startedAt: "2026-04-21T14:18:26Z"
    name: stress-container
    ready: false
    resources:
      limits:
        cpu: 500m
        memory: 128Mi
      requests:
        cpu: 250m
        memory: 64Mi
    restartCount: 32
    started: false
    state:
      waiting:
        message: back-off 5m0s restarting failed container=stress-container pod=resource-pod_default(817a4181-b790-46a7-bd9a-7e297be42f0d)
        reason: CrashLoopBackOff
    volumeMounts:
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-4ll6d
      readOnly: true
      recursiveReadOnly: Disabled
  hostIP: 10.224.0.5
  hostIPs:
  - ip: 10.224.0.5
  observedGeneration: 1
  phase: Running
  podIP: 10.244.0.220
  podIPs:
  - ip: 10.244.0.220
  qosClass: Burstable
  startTime: "2026-04-21T11:53:31Z"
